import{a as b,S as w,i as c}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const M="53379684-45c44d339c561808b5ad44122",v="https://pixabay.com/api/";async function h(o,t=1){const a={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15};try{return(await b.get(v,{params:a})).data}catch(n){return console.log("Error",n),null}}const i={gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".js-loader"),loadMoreBtn:document.querySelector(".js-load-more")},B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const t=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:l,comments:S,downloads:q})=>`
        <li class="gallery-item">
          <a href="${n}">
            <img src="${a}" alt="${e}" />
          </a>
          <ul class="info">
            <li><strong>Likes</strong> ${r}</li>
            <li><strong>Views</strong> ${l}</li>
            <li><strong>Comments</strong> ${S}</li>
            <li><strong>Downloads</strong> ${q}</li>
          </ul>
        </li>`).join("");i.gallery.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){i.gallery.innerHTML=""}function y(){i.loader.classList.remove("hidden")}function u(){i.loader.classList.add("hidden")}function p(){i.loadMoreBtn.classList.remove("hidden")}function g(){i.loadMoreBtn.classList.add("hidden")}const L=document.querySelector(".form"),P=L.querySelector("input[name='search-text']"),R=document.querySelector(".js-load-more");g();let d="",s=1,f=0;L.addEventListener("submit",$);R.addEventListener("click",j);async function $(o){if(o.preventDefault(),d=P.value.trim(),!d){c.error({message:"Please enter a search query!",position:"topRight"});return}s=1,E(),g(),y();try{const t=await h(d,s);if(u(),!t||t.hits.length===0){c.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),f=Math.ceil(t.totalHits/15),s<f&&p()}catch{u(),c.error({message:"Error fetching data. Try again later.",position:"topRight"})}}async function j(){s+=1,g(),y();try{const o=await h(d,s);u(),m(o.hits),O(),s>=f?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),g()):p()}catch{u(),c.error({message:"Error fetching additional images.",position:"topRight"})}}function O(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
